[repository]
name = "hyprscroller-ng"
authors = ["kuroiko0429"]
commit_pins = [
    ["5c9377c15f85c50648f35ca5a213754f95b93ca0", "a58b52fc615a735fb79c89532bc473e563bb2727"], # v0.56.1
]

[hyprscrolling]
description = "A scrolling (column-based) layout plugin for Hyprland"
authors = ["kuroiko0429"]
output = "hyprscrolling.so"
build = [
    "make all",
]
